name: lanka_health_care
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  intl: ^0.19.0
  image_picker_web: ^4.0.0
  cached_network_image: ^3.1.0
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.3
  flutter_html: ^3.0.0-alpha.1
  flutter_web_qrcode_scanner: ^1.1.1
  qr_flutter: ^4.0.0
  path_provider: ^2.0.5

dev_dependencies:
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/logo.png
    - lib/fonts/Nunito-Regular.ttf