name: lanka_health_care
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  intl: ^0.19.0
  image_picker_web: ^4.0.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/logo.png